# Generated by Django 5.0.6 on 2024-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_rename_item_sale_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(default='nairobi', max_length=255),
            preserve_default=False,
        ),
    ]
